title: wuhulamb
author:
  name: wuhulamb
  email: wuhulamb@qq.com
description: >
  记录·分享·表达
timezone: Asia/Shanghai
show_excerpts: false
#excerpt_separator: <!--more-->

collections:
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"


remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

header_pages:
  - category.md
  - motto.md
  - about.md
