title: wuhulamb
author:
  name: wuhulamb
  email: wuhulamb@qq.com
description: >
  记录·分享·表达
timezone: Asia/Shanghai
show_excerpts: true
excerpt_separator: <!--more-->

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - like.md
  - about.md

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/wuhulamb" }
